### ISSUE TITLE
dmx control

### ISSUE THREAD

**Issue by davidd1205** [JonahderTyp/DMXtoWS2812b#1]
hello

i find a software to control my strip ws2812b with my dmx soundswitch 
and your release have no description 
have you a shema about dmx in and out pin and number of channel to control strip led 
thanks

**Comment by JonahderTyp** [comment]
You need an Max485-Module and connect it like [this](https://www.jonasrueter.de/wp-content/uploads/DMX_Empfang_Steckplatine.png) for dmx throughput, you can just Y or T of it. 

You can connect your led strip to any digital pin, it is configured in line 3.

**Comment by davidd1205** [comment]
ok thanks for the shame 
I receive my rs485 tomorrow
and a channel number for control  ?

**Comment by JonahderTyp** [comment]
the channels are hardcoded, you can change the channel the arduino listens for by changing the nuber of the command: 
DMXSerial.read(17);   <= this will get you the value of channel 17 (0 to 255). 
To improve performance you can set DMXSerial.maxChannel(32); to the highest channel +1 you want to listen for, eg: you listen for channels 2,3,4,70,80 , you would use: DMXSerial.maxChannel(81); . idk if it would listen for channel 81, better be save and +1 the max channel.

**Comment by JonahderTyp** [comment]
I have updated the code, since my last commit, it is now up to date. And an note: this code works with my setup, you will have to modify it!
